import { defineModule } from '@xyra/contracts';

/**
 * Frozen v1 table ownership. Append records are immutable journals; schedule configuration is
 * local until WP-CLOUD provides a multi-device lease authority.
 */
export default defineModule({
  id: 'swarm',
  version: '1.0.0',
  pillar: 'SWARM',
  title: 'Swarm',
  description: 'Bounded agent profiles, runs, model routing, evaluations and Night Shift',
  icon: 'bot',
  order: 20,
  requirements: [
    'XIO-REQ-SWM-001',
    'XIO-REQ-SWM-002',
    'XIO-REQ-SWM-003',
    'XIO-REQ-SWM-004',
    'XIO-REQ-SWM-005',
    'XIO-REQ-SWM-006',
    'XIO-REQ-SWM-007',
    'XIO-REQ-SWM-008',
    'REQ-AIS-001',
    'REQ-AIS-002',
    'REQ-AIS-003',
    'REQ-AIS-005',
    'REQ-AIS-006',
    'REQ-AIS-007',
    'REQ-AIS-008',
  ],
  permissions: [
    'swarm:profile:read',
    'swarm:profile:write',
    'swarm:run:read',
    'swarm:run:write',
    'swarm:run:cancel',
    'swarm:night-shift:configure',
  ],
  roleGrants: {
    owner: [
      'swarm:profile:read',
      'swarm:profile:write',
      'swarm:run:read',
      'swarm:run:write',
      'swarm:run:cancel',
      'swarm:night-shift:configure',
    ],
    admin: ['swarm:profile:read', 'swarm:profile:write', 'swarm:run:read', 'swarm:run:write', 'swarm:run:cancel'],
    manager: ['swarm:profile:read', 'swarm:run:read', 'swarm:run:write', 'swarm:run:cancel'],
    member: ['swarm:profile:read', 'swarm:run:read'],
    viewer: ['swarm:profile:read', 'swarm:run:read'],
    auditor: ['swarm:profile:read', 'swarm:run:read'],
  },
  nav: [
    { path: '', title: 'Operations floor', keywords: ['agents', 'runs', 'crew'] },
    { path: 'profiles', title: 'Agent profiles', keywords: ['roles', 'charters'] },
    { path: 'night-shift', title: 'Night Shift', keywords: ['autonomy', 'schedule', 'leash'] },
  ],
  events: {
    emits: ['swarm.run.started', 'swarm.run.terminated', 'swarm.run.tool-denied', 'swarm.night-shift.changed'],
    consumes: ['core.kill-switch.changed'],
  },
  tables: [
    {
      name: 'swarm_agent_profiles',
      class: 'lww',
      authority: 'synced',
      // Privilege-bearing columns are server-checked, never blind device writes.
      guardedColumns: ['capability_grants', 'autonomy_level', 'secret_scopes', 'network_policy', 'filesystem_policy', 'approval_policy', 'eval_history'],
      privilegedColumns: ['capability_grants', 'autonomy_level', 'secret_scopes', 'network_policy', 'filesystem_policy', 'approval_policy', 'eval_history'],
      actorField: 'created_by',
      writePermission: 'swarm:profile:write',
      readPermission: 'swarm:profile:read',
      allowedFields: [
        'role_id',
        'charter',
        'default_provider',
        'default_model',
        'fallbacks',
        'budgets',
        'memory_scope',
        'output_schema',
      ],
      columns: {
        role_id: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 100 },
        charter: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 100_000 },
        default_provider: { type: 'text', requiredOnInsert: true, minLength: 1 },
        default_model: { type: 'text', requiredOnInsert: true, minLength: 1 },
        fallbacks: { type: 'jsonb' },
        budgets: { type: 'jsonb', requiredOnInsert: true },
        memory_scope: { type: 'jsonb', requiredOnInsert: true },
        output_schema: { type: 'jsonb', requiredOnInsert: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'swarm_model_evals',
      class: 'append',
      authority: 'append',
      actorField: 'created_by',
      receivedAtField: 'created_at',
      writePermission: 'swarm:profile:write',
      readPermission: 'swarm:profile:read',
      allowedFields: ['provider', 'model_id', 'eval_id', 'metrics', 'ran_at'],
      columns: {
        provider: { type: 'text', requiredOnInsert: true, minLength: 1 },
        model_id: { type: 'text', requiredOnInsert: true, minLength: 1 },
        eval_id: { type: 'text', requiredOnInsert: true, minLength: 1 },
        metrics: { type: 'jsonb', requiredOnInsert: true },
        ran_at: { type: 'timestamptz', requiredOnInsert: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    {
      name: 'swarm_runs',
      class: 'append',
      authority: 'append',
      children: ['swarm_run_journal', 'swarm_run_outcomes'],
      actorField: 'created_by',
      receivedAtField: 'created_at',
      writePermission: 'swarm:run:write',
      readPermission: 'swarm:run:read',
      // Start record only; the terminal summary is the separate swarm_run_outcomes row.
      allowedFields: ['profile_id', 'parent_run_id', 'budgets', 'started_at'],
      columns: {
        profile_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'swarm_agent_profiles' } },
        parent_run_id: { type: 'uuid', nullable: true, references: { table: 'swarm_runs' } },
        budgets: { type: 'jsonb', requiredOnInsert: true },
        started_at: { type: 'timestamptz', requiredOnInsert: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    {
      name: 'swarm_run_outcomes',
      class: 'append',
      authority: 'append',
      actorField: 'created_by',
      receivedAtField: 'created_at',
      writePermission: 'swarm:run:write',
      readPermission: 'swarm:run:read',
      allowedFields: ['run_id', 'termination', 'output', 'iterations', 'actions', 'failures', 'cost_usd', 'ended_at'],
      columns: {
        run_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'swarm_runs' } },
        termination: { type: 'text', requiredOnInsert: true },
        output: { type: 'text', nullable: true },
        iterations: { type: 'integer', requiredOnInsert: true, min: '0' },
        actions: { type: 'integer', requiredOnInsert: true, min: '0' },
        failures: { type: 'integer', requiredOnInsert: true, min: '0' },
        cost_usd: { type: 'numeric', requiredOnInsert: true, min: '0', scale: 6 },
        ended_at: { type: 'timestamptz', requiredOnInsert: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    {
      name: 'swarm_run_journal',
      class: 'append',
      authority: 'append',
      actorField: 'created_by',
      receivedAtField: 'created_at',
      writePermission: 'swarm:run:write',
      readPermission: 'swarm:run:read',
      allowedFields: ['run_id', 'seq', 'event_type', 'detail', 'occurred_at'],
      columns: {
        run_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'swarm_runs' } },
        seq: { type: 'integer', requiredOnInsert: true, min: '0' },
        event_type: { type: 'text', requiredOnInsert: true, minLength: 1 },
        detail: { type: 'jsonb' },
        occurred_at: { type: 'timestamptz', requiredOnInsert: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    {
      name: 'swarm_prompt_versions',
      class: 'append',
      authority: 'append',
      actorField: 'created_by',
      receivedAtField: 'created_at',
      writePermission: 'swarm:profile:write',
      readPermission: 'swarm:profile:read',
      allowedFields: ['prompt_id', 'version', 'purpose', 'template', 'required_capabilities', 'output_contract', 'retired_at'],
      columns: {
        prompt_id: { type: 'text', requiredOnInsert: true, minLength: 1 },
        version: { type: 'integer', requiredOnInsert: true, min: '1' },
        purpose: { type: 'text', requiredOnInsert: true, minLength: 1 },
        template: { type: 'text', requiredOnInsert: true, minLength: 1 },
        required_capabilities: { type: 'jsonb' },
        output_contract: { type: 'jsonb', nullable: true },
        retired_at: { type: 'timestamptz', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    { name: 'swarm_night_shift', class: 'local', authority: 'local' },
  ],
  dataClassification: 'confidential',
});
