// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/ApprovalRequiredBody
export type ApprovalRequiredBody = z.input<typeof ApprovalRequiredBody>;
export type ApprovalRequiredBodyOutput = z.output<typeof ApprovalRequiredBody>;
