// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/AutonomyLevel
export type AutonomyLevel = z.input<typeof AutonomyLevel>;
export type AutonomyLevelOutput = z.output<typeof AutonomyLevel>;
