// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/CapabilityKind
export type CapabilityKind = z.input<typeof CapabilityKind>;
export type CapabilityKindOutput = z.output<typeof CapabilityKind>;
