// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/CatalogEntry
export type CatalogEntry = z.input<typeof CatalogEntry>;
export type CatalogEntryOutput = z.output<typeof CatalogEntry>;
