// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/ConnectorState
export type ConnectorState = z.input<typeof ConnectorState>;
export type ConnectorStateOutput = z.output<typeof ConnectorState>;
