// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/ConnectorStatus
export type ConnectorStatus = z.input<typeof ConnectorStatus>;
export type ConnectorStatusOutput = z.output<typeof ConnectorStatus>;
