// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/DecimalString
export type DecimalString = z.input<typeof DecimalString>;
export type DecimalStringOutput = z.output<typeof DecimalString>;
