// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/Environment
export type Environment = z.input<typeof Environment>;
export type EnvironmentOutput = z.output<typeof Environment>;
