// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/NavEntry
export type NavEntry = z.input<typeof NavEntry>;
export type NavEntryOutput = z.output<typeof NavEntry>;
