// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/Pillar
export type Pillar = z.input<typeof Pillar>;
export type PillarOutput = z.output<typeof Pillar>;
