// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/Principal
export type Principal = z.input<typeof Principal>;
export type PrincipalOutput = z.output<typeof Principal>;
