// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/PullResponse
export type PullResponse = z.input<typeof PullResponse>;
export type PullResponseOutput = z.output<typeof PullResponse>;
