// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/PushResponse
export type PushResponse = z.input<typeof PushResponse>;
export type PushResponseOutput = z.output<typeof PushResponse>;
