// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/RowChange
export type RowChange = z.input<typeof RowChange>;
export type RowChangeOutput = z.output<typeof RowChange>;
