// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/SyncState
export type SyncState = z.input<typeof SyncState>;
export type SyncStateOutput = z.output<typeof SyncState>;
