// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/TableDecl
export type TableDecl = z.input<typeof TableDecl>;
export type TableDeclOutput = z.output<typeof TableDecl>;
