// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/WidgetDecl
export type WidgetDecl = z.input<typeof WidgetDecl>;
export type WidgetDeclOutput = z.output<typeof WidgetDecl>;
