// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/WorkspaceRole
export type WorkspaceRole = z.input<typeof WorkspaceRole>;
export type WorkspaceRoleOutput = z.output<typeof WorkspaceRole>;
