import { defineModule } from '@xyra/contracts';

export default defineModule({
  id: 'comms',
  version: '1.0.0',
  pillar: 'CONNECT',
  title: 'Comms',
  description: 'Unified inbox, calendar, meetings and outbound with approval gates',
  icon: 'inbox',
  order: 20,
  requirements: [
    'REQ-005',
    'REQ-PAR-002',
    'PAR-XIO-080',
    'PAR-XIO-081',
    'PAR-XIO-082',
    'PAR-XIO-083',
  ],
  permissions: [
    'comms:thread:read',
    'comms:thread:write',
    'comms:thread:send',
    'comms:event:read',
    'comms:event:write',
    'comms:meeting:read',
    'comms:meeting:write',
    'comms:recording:read',
  ],
  roleGrants: {
    manager: [
      'comms:thread:read',
      'comms:thread:write',
      'comms:thread:send',
      'comms:event:read',
      'comms:event:write',
      'comms:meeting:read',
      'comms:meeting:write',
      'comms:recording:read',
    ],
    member: [
      'comms:thread:read',
      'comms:thread:write',
      'comms:thread:send',
      'comms:event:read',
      'comms:event:write',
      'comms:meeting:read',
      'comms:recording:read',
    ],
    viewer: [
      'comms:thread:read',
      'comms:event:read',
      'comms:meeting:read',
    ],
    auditor: [
      'comms:thread:read',
      'comms:event:read',
      'comms:meeting:read',
    ],
  },
  nav: [
    { path: '', title: 'Inbox', keywords: ['messages', 'email', 'threads', 'triage'] },
    { path: 'calendar', title: 'Calendar', keywords: ['schedule', 'events', 'meetings'] },
    { path: 'meetings', title: 'Meetings', keywords: ['recordings', 'follow-ups', 'notes'] },
  ],
  dependsOn: ['core'],
  tables: [
    {
      name: 'comms_threads',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'comms:thread:write',
      readPermission: 'comms:thread:read',
      allowedFields: ['subject', 'channel', 'status', 'participants', 'labels', 'snoozed_until'],
      columns: {
        subject: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 500 },
        channel: { type: 'text', requiredOnInsert: true, enum: ['email', 'slack', 'sms', 'in_app'] },
        status: { type: 'text', enum: ['open', 'snoozed', 'done'] },
        participants: { type: 'jsonb' },
        labels: { type: 'jsonb' },
        snoozed_until: { type: 'timestamptz', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'comms_messages',
      class: 'append',
      authority: 'append',
      actorField: 'created_by',
      writePermission: 'comms:thread:write',
      readPermission: 'comms:thread:read',
      receivedAtField: 'created_at',
      allowedFields: ['thread_id', 'body', 'direction', 'external_id', 'send_approval_id'],
      columns: {
        thread_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'comms_threads' } },
        body: { type: 'text', requiredOnInsert: true },
        direction: { type: 'text', requiredOnInsert: true, enum: ['inbound', 'outbound'] },
        external_id: { type: 'text', nullable: true },
        send_approval_id: { type: 'uuid', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    {
      name: 'comms_events',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'comms:event:write',
      readPermission: 'comms:event:read',
      allowedFields: ['title', 'description', 'starts_at', 'ends_at', 'location', 'attendees', 'status'],
      columns: {
        title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 300 },
        description: { type: 'text', nullable: true },
        starts_at: { type: 'timestamptz', requiredOnInsert: true },
        ends_at: { type: 'timestamptz', requiredOnInsert: true },
        location: { type: 'text', nullable: true },
        attendees: { type: 'jsonb' },
        status: { type: 'text', enum: ['tentative', 'confirmed', 'cancelled'] },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'comms_meetings',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'comms:meeting:write',
      readPermission: 'comms:meeting:read',
      allowedFields: ['title', 'event_id', 'summary', 'action_items', 'recording_url'],
      columns: {
        title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 300 },
        event_id: { type: 'uuid', nullable: true, references: { table: 'comms_events' } },
        summary: { type: 'text', nullable: true },
        action_items: { type: 'jsonb' },
        recording_url: { type: 'text', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
  ],
  portedFrom: ['FounderOS (MIT) @ ad46d77'],
});
