// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/ApprovalStatus
export type ApprovalStatus = z.input<typeof ApprovalStatus>;
export type ApprovalStatusOutput = z.output<typeof ApprovalStatus>;
