// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/ApprovalRecord
export type ApprovalRecord = z.input<typeof ApprovalRecord>;
export type ApprovalRecordOutput = z.output<typeof ApprovalRecord>;
