// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/AuditEvent
export type AuditEvent = z.input<typeof AuditEvent>;
export type AuditEventOutput = z.output<typeof AuditEvent>;
