// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/DataClassification
export type DataClassification = z.input<typeof DataClassification>;
export type DataClassificationOutput = z.output<typeof DataClassification>;
