// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/EventEnvelope
export type EventEnvelope = z.input<typeof EventEnvelope>;
export type EventEnvelopeOutput = z.output<typeof EventEnvelope>;
