// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/FieldWrite
export type FieldWrite = z.input<typeof FieldWrite>;
export type FieldWriteOutput = z.output<typeof FieldWrite>;
