// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/KillSwitchState
export type KillSwitchState = z.input<typeof KillSwitchState>;
export type KillSwitchStateOutput = z.output<typeof KillSwitchState>;
