// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/ModuleManifest
export type ModuleManifest = z.input<typeof ModuleManifest>;
export type ModuleManifestOutput = z.output<typeof ModuleManifest>;
