// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/PaletteCommand
export type PaletteCommand = z.input<typeof PaletteCommand>;
export type PaletteCommandOutput = z.output<typeof PaletteCommand>;
