// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/Permission
export type Permission = z.input<typeof Permission>;
export type PermissionOutput = z.output<typeof Permission>;
