// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/PushRequest
export type PushRequest = z.input<typeof PushRequest>;
export type PushRequestOutput = z.output<typeof PushRequest>;
