// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/RiskClass
export type RiskClass = z.input<typeof RiskClass>;
export type RiskClassOutput = z.output<typeof RiskClass>;
