// GENERATED by tools/gen-type-translations.mjs - do not edit.
// Source: packages/contracts/src/WorkspaceKind
export type WorkspaceKind = z.input<typeof WorkspaceKind>;
export type WorkspaceKindOutput = z.output<typeof WorkspaceKind>;
