import { defineModule } from '@xyra/contracts';

export default defineModule({
  id: 'growth',
  version: '1.0.0',
  pillar: 'GROWTH',
  title: 'Growth',
  description: 'CRM, outreach, funnels, ads and brand deals',
  icon: 'trending-up',
  order: 30,
  requirements: [
    'REQ-006',
    'REQ-007',
    'REQ-PAR-003',
    'PAR-XIO-090',
    'PAR-XIO-091',
    'PAR-XIO-092',
    'PAR-XIO-093',
    'PAR-XIO-094',
  ],
  permissions: [
    'growth:contact:read',
    'growth:contact:write',
    'growth:deal:read',
    'growth:deal:write',
    'growth:sequence:read',
    'growth:sequence:write',
    'growth:sequence:send',
    'growth:funnel:read',
    'growth:funnel:write',
    'growth:content:read',
    'growth:content:write',
    'growth:content:publish',
    'growth:ad:read',
    'growth:ad:write',
    'growth:ad:spend',
    'growth:brand:read',
    'growth:brand:write',
  ],
  roleGrants: {
    manager: [
      'growth:contact:read',
      'growth:contact:write',
      'growth:deal:read',
      'growth:deal:write',
      'growth:sequence:read',
      'growth:sequence:write',
      'growth:sequence:send',
      'growth:funnel:read',
      'growth:funnel:write',
      'growth:content:read',
      'growth:content:write',
      'growth:content:publish',
      'growth:ad:read',
      'growth:ad:write',
      'growth:ad:spend',
      'growth:brand:read',
      'growth:brand:write',
    ],
    member: [
      'growth:contact:read',
      'growth:contact:write',
      'growth:deal:read',
      'growth:deal:write',
      'growth:sequence:read',
      'growth:sequence:write',
      'growth:funnel:read',
      'growth:content:read',
      'growth:content:write',
      'growth:ad:read',
      'growth:brand:read',
    ],
    viewer: [
      'growth:contact:read',
      'growth:deal:read',
      'growth:sequence:read',
      'growth:funnel:read',
      'growth:content:read',
      'growth:ad:read',
      'growth:brand:read',
    ],
    auditor: [
      'growth:contact:read',
      'growth:deal:read',
      'growth:funnel:read',
      'growth:ad:read',
    ],
  },
  nav: [
    { path: '', title: 'CRM', keywords: ['contacts', 'companies', 'deals', 'pipeline'] },
    { path: 'sequences', title: 'Sequences', keywords: ['outreach', 'campaigns', 'email'] },
    { path: 'funnels', title: 'Funnels', keywords: ['conversion', 'neural flow', 'radial wheel'] },
    { path: 'content', title: 'Content', keywords: ['social', 'calendar', 'posts', 'publishing'] },
    { path: 'ads', title: 'Ads', keywords: ['adpilot', 'spend', 'campaigns', 'autonomy'] },
    { path: 'brand-deals', title: 'Brand Deals', keywords: ['partnerships', 'sponsorships', 'collaborations'] },
  ],
  dependsOn: ['core'],
  tables: [
    {
      name: 'growth_contacts',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'growth:contact:write',
      readPermission: 'growth:contact:read',
      allowedFields: ['name', 'email', 'phone', 'company_id', 'segment', 'tags', 'custom'],
      columns: {
        name: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 300 },
        email: { type: 'text', nullable: true, maxLength: 320 },
        phone: { type: 'text', nullable: true, maxLength: 30 },
        company_id: { type: 'uuid', nullable: true, references: { table: 'growth_companies' } },
        segment: { type: 'text', nullable: true, maxLength: 100 },
        tags: { type: 'jsonb' },
        custom: { type: 'jsonb' },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'growth_companies',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'growth:contact:write',
      readPermission: 'growth:contact:read',
      allowedFields: ['name', 'domain', 'industry', 'size_band', 'tags', 'custom'],
      columns: {
        name: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 300 },
        domain: { type: 'text', nullable: true, maxLength: 253 },
        industry: { type: 'text', nullable: true, maxLength: 100 },
        size_band: { type: 'text', nullable: true, enum: ['1-10', '11-50', '51-200', '201-1000', '1001+'] },
        tags: { type: 'jsonb' },
        custom: { type: 'jsonb' },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'growth_deals',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'growth:deal:write',
      readPermission: 'growth:deal:read',
      allowedFields: ['title', 'contact_id', 'company_id', 'pipeline', 'stage', 'value_cents', 'currency', 'expected_close_at', 'status'],
      columns: {
        title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 300 },
        contact_id: { type: 'uuid', nullable: true, references: { table: 'growth_contacts' } },
        company_id: { type: 'uuid', nullable: true, references: { table: 'growth_companies' } },
        pipeline: { type: 'text', requiredOnInsert: true, maxLength: 100 },
        stage: { type: 'text', requiredOnInsert: true, maxLength: 100 },
        value_cents: { type: 'integer', nullable: true },
        currency: { type: 'text', maxLength: 3, nullable: true },
        expected_close_at: { type: 'timestamptz', nullable: true },
        status: { type: 'text', enum: ['open', 'won', 'lost'] },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'growth_sequences',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'growth:sequence:write',
      readPermission: 'growth:sequence:read',
      allowedFields: ['name', 'description', 'steps', 'status', 'send_approval_policy'],
      columns: {
        name: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 200 },
        description: { type: 'text', nullable: true },
        steps: { type: 'jsonb' },
        status: { type: 'text', enum: ['draft', 'active', 'paused', 'archived'] },
        send_approval_policy: { type: 'text', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'growth_sequence_enrollments',
      class: 'append',
      authority: 'append',
      actorField: 'created_by',
      writePermission: 'growth:sequence:write',
      readPermission: 'growth:sequence:read',
      receivedAtField: 'created_at',
      allowedFields: ['sequence_id', 'contact_id', 'send_approval_id'],
      columns: {
        sequence_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'growth_sequences' } },
        contact_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'growth_contacts' } },
        send_approval_id: { type: 'uuid', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    {
      name: 'growth_funnels',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'growth:funnel:write',
      readPermission: 'growth:funnel:read',
      allowedFields: ['name', 'kind', 'stages', 'metrics'],
      columns: {
        name: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 200 },
        kind: { type: 'text', requiredOnInsert: true, enum: ['neural', 'radial', 'linear'] },
        stages: { type: 'jsonb' },
        metrics: { type: 'jsonb' },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'growth_content_posts',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'growth:content:write',
      readPermission: 'growth:content:read',
      allowedFields: ['title', 'body', 'channels', 'scheduled_at', 'status', 'publish_approval_id'],
      columns: {
        title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 300 },
        body: { type: 'text', requiredOnInsert: true },
        channels: { type: 'jsonb' },
        scheduled_at: { type: 'timestamptz', nullable: true },
        status: { type: 'text', enum: ['draft', 'scheduled', 'published', 'failed'] },
        publish_approval_id: { type: 'uuid', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'growth_ad_campaigns',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'growth:ad:write',
      readPermission: 'growth:ad:read',
      allowedFields: ['name', 'platform', 'autonomy_mode', 'daily_budget_cents', 'total_budget_cents', 'currency', 'status', 'spend_approval_policy'],
      columns: {
        name: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 200 },
        platform: { type: 'text', requiredOnInsert: true, enum: ['google', 'meta', 'linkedin', 'tiktok', 'other'] },
        autonomy_mode: { type: 'text', enum: ['manual', 'supervised', 'autonomous'] },
        daily_budget_cents: { type: 'integer', nullable: true },
        total_budget_cents: { type: 'integer', nullable: true },
        currency: { type: 'text', maxLength: 3, nullable: true },
        status: { type: 'text', enum: ['draft', 'active', 'paused', 'ended'] },
        spend_approval_policy: { type: 'text', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'growth_brand_deals',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'growth:brand:write',
      readPermission: 'growth:brand:read',
      allowedFields: ['title', 'partner_name', 'partner_contact', 'value_cents', 'currency', 'deliverables', 'starts_at', 'ends_at', 'status'],
      columns: {
        title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 300 },
        partner_name: { type: 'text', requiredOnInsert: true, maxLength: 300 },
        partner_contact: { type: 'text', nullable: true, maxLength: 320 },
        value_cents: { type: 'integer', nullable: true },
        currency: { type: 'text', maxLength: 3, nullable: true },
        deliverables: { type: 'jsonb' },
        starts_at: { type: 'timestamptz', nullable: true },
        ends_at: { type: 'timestamptz', nullable: true },
        status: { type: 'text', enum: ['prospecting', 'negotiating', 'active', 'completed', 'cancelled'] },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
  ],
  portedFrom: ['FounderOS (MIT) @ ad46d77'],
});
