// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { ApprovalRequiredBody } from '@xyra/contracts';
import type { z } from 'zod';
export type ApprovalRequiredBody = z.input<typeof ApprovalRequiredBody>;
export type ApprovalRequiredBodyOutput = z.output<typeof ApprovalRequiredBody>;
export { ApprovalRequiredBody };
export function ApprovalRequiredBodyJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(ApprovalRequiredBody.jsonSchema()));
}
