// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { ApprovalRecord } from '@xyra/contracts';
import type { z } from 'zod';
export type ApprovalRecord = z.input<typeof ApprovalRecord>;
export type ApprovalRecordOutput = z.output<typeof ApprovalRecord>;
export { ApprovalRecord };
export function ApprovalRecordJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(ApprovalRecord.jsonSchema()));
}
