// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { ApprovalStatus } from '@xyra/contracts';
import type { z } from 'zod';
export type ApprovalStatus = z.input<typeof ApprovalStatus>;
export type ApprovalStatusOutput = z.output<typeof ApprovalStatus>;
export { ApprovalStatus };
export function ApprovalStatusJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(ApprovalStatus.jsonSchema()));
}
