// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { AuditEvent } from '@xyra/contracts';
import type { z } from 'zod';
export type AuditEvent = z.input<typeof AuditEvent>;
export type AuditEventOutput = z.output<typeof AuditEvent>;
export { AuditEvent };
export function AuditEventJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(AuditEvent.jsonSchema()));
}
