// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { AutonomyLevel } from '@xyra/contracts';
import type { z } from 'zod';
export type AutonomyLevel = z.input<typeof AutonomyLevel>;
export type AutonomyLevelOutput = z.output<typeof AutonomyLevel>;
export { AutonomyLevel };
export function AutonomyLevelJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(AutonomyLevel.jsonSchema()));
}
