// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { CapabilityKind } from '@xyra/contracts';
import type { z } from 'zod';
export type CapabilityKind = z.input<typeof CapabilityKind>;
export type CapabilityKindOutput = z.output<typeof CapabilityKind>;
export { CapabilityKind };
export function CapabilityKindJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(CapabilityKind.jsonSchema()));
}
