// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { CatalogEntry } from '@xyra/contracts';
import type { z } from 'zod';
export type CatalogEntry = z.input<typeof CatalogEntry>;
export type CatalogEntryOutput = z.output<typeof CatalogEntry>;
export { CatalogEntry };
export function CatalogEntryJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(CatalogEntry.jsonSchema()));
}
