// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { ConnectorState } from '@xyra/contracts';
import type { z } from 'zod';
export type ConnectorState = z.input<typeof ConnectorState>;
export type ConnectorStateOutput = z.output<typeof ConnectorState>;
export { ConnectorState };
export function ConnectorStateJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(ConnectorState.jsonSchema()));
}
