// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { ConnectorStatus } from '@xyra/contracts';
import type { z } from 'zod';
export type ConnectorStatus = z.input<typeof ConnectorStatus>;
export type ConnectorStatusOutput = z.output<typeof ConnectorStatus>;
export { ConnectorStatus };
export function ConnectorStatusJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(ConnectorStatus.jsonSchema()));
}
