// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { DataClassification } from '@xyra/contracts';
import type { z } from 'zod';
export type DataClassification = z.input<typeof DataClassification>;
export type DataClassificationOutput = z.output<typeof DataClassification>;
export { DataClassification };
export function DataClassificationJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(DataClassification.jsonSchema()));
}
