// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { DecimalString } from '@xyra/contracts';
import type { z } from 'zod';
export type DecimalString = z.input<typeof DecimalString>;
export type DecimalStringOutput = z.output<typeof DecimalString>;
export { DecimalString };
export function DecimalStringJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(DecimalString.jsonSchema()));
}
