// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { Environment } from '@xyra/contracts';
import type { z } from 'zod';
export type Environment = z.input<typeof Environment>;
export type EnvironmentOutput = z.output<typeof Environment>;
export { Environment };
export function EnvironmentJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(Environment.jsonSchema()));
}
