// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { EventEnvelope } from '@xyra/contracts';
import type { z } from 'zod';
export type EventEnvelope = z.input<typeof EventEnvelope>;
export type EventEnvelopeOutput = z.output<typeof EventEnvelope>;
export { EventEnvelope };
export function EventEnvelopeJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(EventEnvelope.jsonSchema()));
}
