// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { FieldWrite } from '@xyra/contracts';
import type { z } from 'zod';
export type FieldWrite = z.input<typeof FieldWrite>;
export type FieldWriteOutput = z.output<typeof FieldWrite>;
export { FieldWrite };
export function FieldWriteJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(FieldWrite.jsonSchema()));
}
