// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { KillSwitchState } from '@xyra/contracts';
import type { z } from 'zod';
export type KillSwitchState = z.input<typeof KillSwitchState>;
export type KillSwitchStateOutput = z.output<typeof KillSwitchState>;
export { KillSwitchState };
export function KillSwitchStateJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(KillSwitchState.jsonSchema()));
}
