// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { ModuleManifest } from '@xyra/contracts';
import type { z } from 'zod';
export type ModuleManifest = z.input<typeof ModuleManifest>;
export type ModuleManifestOutput = z.output<typeof ModuleManifest>;
export { ModuleManifest };
export function ModuleManifestJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(ModuleManifest.jsonSchema()));
}
