// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { NavEntry } from '@xyra/contracts';
import type { z } from 'zod';
export type NavEntry = z.input<typeof NavEntry>;
export type NavEntryOutput = z.output<typeof NavEntry>;
export { NavEntry };
export function NavEntryJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(NavEntry.jsonSchema()));
}
