// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { PaletteCommand } from '@xyra/contracts';
import type { z } from 'zod';
export type PaletteCommand = z.input<typeof PaletteCommand>;
export type PaletteCommandOutput = z.output<typeof PaletteCommand>;
export { PaletteCommand };
export function PaletteCommandJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(PaletteCommand.jsonSchema()));
}
