// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { Permission } from '@xyra/contracts';
import type { z } from 'zod';
export type Permission = z.input<typeof Permission>;
export type PermissionOutput = z.output<typeof Permission>;
export { Permission };
export function PermissionJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(Permission.jsonSchema()));
}
