// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { Pillar } from '@xyra/contracts';
import type { z } from 'zod';
export type Pillar = z.input<typeof Pillar>;
export type PillarOutput = z.output<typeof Pillar>;
export { Pillar };
export function PillarJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(Pillar.jsonSchema()));
}
