// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { Principal } from '@xyra/contracts';
import type { z } from 'zod';
export type Principal = z.input<typeof Principal>;
export type PrincipalOutput = z.output<typeof Principal>;
export { Principal };
export function PrincipalJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(Principal.jsonSchema()));
}
