// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { PullResponse } from '@xyra/contracts';
import type { z } from 'zod';
export type PullResponse = z.input<typeof PullResponse>;
export type PullResponseOutput = z.output<typeof PullResponse>;
export { PullResponse };
export function PullResponseJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(PullResponse.jsonSchema()));
}
