// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { PushResponse } from '@xyra/contracts';
import type { z } from 'zod';
export type PushResponse = z.input<typeof PushResponse>;
export type PushResponseOutput = z.output<typeof PushResponse>;
export { PushResponse };
export function PushResponseJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(PushResponse.jsonSchema()));
}
