// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { PushRequest } from '@xyra/contracts';
import type { z } from 'zod';
export type PushRequest = z.input<typeof PushRequest>;
export type PushRequestOutput = z.output<typeof PushRequest>;
export { PushRequest };
export function PushRequestJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(PushRequest.jsonSchema()));
}
