// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { RiskClass } from '@xyra/contracts';
import type { z } from 'zod';
export type RiskClass = z.input<typeof RiskClass>;
export type RiskClassOutput = z.output<typeof RiskClass>;
export { RiskClass };
export function RiskClassJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(RiskClass.jsonSchema()));
}
