// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { RowChange } from '@xyra/contracts';
import type { z } from 'zod';
export type RowChange = z.input<typeof RowChange>;
export type RowChangeOutput = z.output<typeof RowChange>;
export { RowChange };
export function RowChangeJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(RowChange.jsonSchema()));
}
