// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { SyncState } from '@xyra/contracts';
import type { z } from 'zod';
export type SyncState = z.input<typeof SyncState>;
export type SyncStateOutput = z.output<typeof SyncState>;
export { SyncState };
export function SyncStateJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(SyncState.jsonSchema()));
}
