// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { TableDecl } from '@xyra/contracts';
import type { z } from 'zod';
export type TableDecl = z.input<typeof TableDecl>;
export type TableDeclOutput = z.output<typeof TableDecl>;
export { TableDecl };
export function TableDeclJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(TableDecl.jsonSchema()));
}
