// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { WidgetDecl } from '@xyra/contracts';
import type { z } from 'zod';
export type WidgetDecl = z.input<typeof WidgetDecl>;
export type WidgetDeclOutput = z.output<typeof WidgetDecl>;
export { WidgetDecl };
export function WidgetDeclJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(WidgetDecl.jsonSchema()));
}
