// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { WorkspaceKind } from '@xyra/contracts';
import type { z } from 'zod';
export type WorkspaceKind = z.input<typeof WorkspaceKind>;
export type WorkspaceKindOutput = z.output<typeof WorkspaceKind>;
export { WorkspaceKind };
export function WorkspaceKindJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(WorkspaceKind.jsonSchema()));
}
