// GENERATED by tools/gen-type-translations.mjs - do not edit.
import { WorkspaceRole } from '@xyra/contracts';
import type { z } from 'zod';
export type WorkspaceRole = z.input<typeof WorkspaceRole>;
export type WorkspaceRoleOutput = z.output<typeof WorkspaceRole>;
export { WorkspaceRole };
export function WorkspaceRoleJsonSchema(): unknown {
  return JSON.parse(JSON.stringify(WorkspaceRole.jsonSchema()));
}
