import { defineCapability } from '@xyra/contracts';
import { z } from 'zod';

const Uuid=z.uuid();
const Entity=z.object({id:Uuid,legal_name:z.string(),jurisdiction:z.string(),registration_number:z.string().nullable(),entity_type:z.enum(['corporation','llc','partnership','trust','other']),parent_entity_id:Uuid.nullable(),status:z.enum(['active','dissolved','inactive'])});
const Resolution=z.object({id:Uuid,title:z.string(),status:z.enum(['draft','approved','rejected']),votes_for:z.number().int(),votes_against:z.number().int(),votes_abstain:z.number().int(),content_hash:z.string().nullable()});

export const corporateCapabilities={
 entities:defineCapability({id:'corporate.entity.list',title:'Legal entities',description:'List legal entities in the workspace',kind:'read',permission:'corporate:entity:read',input:z.object({}),output:z.array(Entity)}),
 createEntity:defineCapability({id:'corporate.entity.create',title:'Create legal entity',description:'Create a scoped legal entity record',kind:'write',permission:'corporate:entity:write',input:z.object({legalName:z.string().trim().min(1).max(240),jurisdiction:z.string().trim().min(2).max(80),registrationNumber:z.string().max(120).nullable().default(null),entityType:z.enum(['corporation','llc','partnership','trust','other']),parentEntityId:Uuid.nullable().default(null)}),output:Entity}),
 setOwnership:defineCapability({id:'corporate.ownership.set',title:'Record ownership',description:'Record an owner share after validating total ownership does not exceed 100 percent',kind:'write',permission:'corporate:ownership:write',input:z.object({entityId:Uuid,ownerEntityId:Uuid.nullable(),ownerRef:z.string().max(200).nullable(),ownershipBps:z.number().int().min(0).max(10000),validFrom:z.iso.date()}),output:z.object({id:Uuid,ownership_bps:z.number().int(),total_bps:z.number().int()})}),
 consolidation:defineCapability({id:'corporate.ledger.consolidate',title:'Entity consolidation',description:'Aggregate ledger balances for selected entities and eliminate tagged intercompany correlations',kind:'read',permission:'corporate:ledger:read',input:z.object({entityIds:z.array(Uuid).min(1).max(100),environment:z.enum(['actual','paper'])}),output:z.array(z.object({asset:z.string(),account_code:z.string(),account_type:z.enum(['asset','liability','equity','income','expense']),units:z.string()}))}),
 approveResolution:defineCapability({id:'corporate.governance.adopt',title:'Adopt resolution',description:'Adopt a board resolution only after quorum and hash its final record',kind:'consequential',permission:'corporate:governance:write',approvalPolicy:'corporate.board.adopt',input:z.object({resolutionId:Uuid,votesFor:z.number().int().min(0),votesAgainst:z.number().int().min(0),votesAbstain:z.number().int().min(0)}),output:Resolution.nullable()}),
 okrRollup:defineCapability({id:'corporate.okr.rollup',title:'OKR progress',description:'Compute deterministic key result progress for an objective',kind:'read',permission:'corporate:okr:read',input:z.object({objectiveId:Uuid}),output:z.object({objectiveId:Uuid,progressBps:z.number().int().min(0).max(10000),keyResultCount:z.number().int()})}),
 overdueCompliance:defineCapability({id:'corporate.compliance.overdue',title:'Overdue compliance',description:'List overdue filings and control evidence obligations',kind:'read',permission:'corporate:compliance:read',input:z.object({asOf:z.iso.date().optional()}),output:z.array(z.object({id:Uuid,title:z.string(),due_on:z.string(),owner_ref:z.string(),days_overdue:z.number().int()}))}),
 orgChart:defineCapability({id:'corporate.org.chart',title:'Organization chart',description:'List reporting lines for people, teams and agents',kind:'read',permission:'corporate:org:read',input:z.object({}),output:z.array(z.object({person_id:Uuid,manager_id:Uuid}))}),
 capTable:defineCapability({id:'corporate.equity.dilution',title:'Dilution scenario',description:'Calculate post-issuance ownership percentages using exact integer units',kind:'read',permission:'corporate:equity:read',input:z.object({shareClassId:Uuid,newUnits:z.string().regex(/^(0|[1-9]\d{0,37})$/)}),output:z.array(z.object({holder_ref:z.string(),units:z.string(),ownership_bps:z.number().int()}))}),
 approvalPolicies:defineCapability({id:'corporate.approval.match',title:'Approval policy match',description:'Resolve matching approval policies for a capability and amount',kind:'read',permission:'corporate:approval:read',input:z.object({capabilityId:z.string().min(1),amountUnits:z.string().regex(/^(0|[1-9]\d{0,37})$/),asset:z.string().min(1)}),output:z.array(z.object({id:Uuid,approver_refs:z.array(z.string()),minimum_approvers:z.number().int()}))}),
 audit:defineCapability({id:'corporate.audit.search',title:'Audit explorer',description:'Search the append-only platform audit log in this workspace',kind:'read',permission:'corporate:audit:read',input:z.object({from:z.iso.datetime({offset:true}).optional(),to:z.iso.datetime({offset:true}).optional(),limit:z.number().int().min(1).max(500).default(100)}),output:z.array(z.record(z.string(),z.unknown()))}),
} as const;
