-- Neon is the durable v1 source of truth for Cloud sync. WorkspaceHub holds
-- only the cached workspace high-water mark and live socket coordination.
CREATE TABLE cloud_sync_sequences (
  tenant_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  last_seq bigint NOT NULL DEFAULT 0 CHECK (last_seq >= 0),
  PRIMARY KEY (tenant_id, workspace_id),
  FOREIGN KEY (tenant_id, workspace_id) REFERENCES workspaces(tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE cloud_sync_rows (
  tenant_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  table_name text NOT NULL CHECK (table_name ~ '^[a-z][a-z0-9_]*$'),
  row_id uuid NOT NULL,
  fields jsonb NOT NULL CHECK (jsonb_typeof(fields) = 'object'),
  deleted_hlc text CHECK (deleted_hlc IS NULL OR deleted_hlc ~ '^[0-9]{13}-[0-9a-f]{4}-[a-z0-9]{1,32}$'),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, workspace_id, table_name, row_id),
  FOREIGN KEY (tenant_id, workspace_id) REFERENCES workspaces(tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE cloud_sync_field_seq (
  tenant_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  table_name text NOT NULL,
  row_id uuid NOT NULL,
  field_name text NOT NULL,
  server_seq bigint NOT NULL CHECK (server_seq > 0),
  PRIMARY KEY (tenant_id, workspace_id, table_name, row_id, field_name),
  FOREIGN KEY (tenant_id, workspace_id) REFERENCES workspaces(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX cloud_sync_field_seq_server_seq ON cloud_sync_field_seq(tenant_id, workspace_id, server_seq);

CREATE TABLE cloud_sync_changes (
  tenant_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  server_seq bigint NOT NULL CHECK (server_seq > 0),
  table_name text NOT NULL CHECK (table_name ~ '^[a-z][a-z0-9_]*$'),
  row_id uuid NOT NULL,
  change jsonb NOT NULL CHECK (jsonb_typeof(change) = 'object'),
  bytes integer NOT NULL CHECK (bytes >= 0),
  PRIMARY KEY (tenant_id, workspace_id, server_seq),
  FOREIGN KEY (tenant_id, workspace_id) REFERENCES workspaces(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX cloud_sync_changes_table_seq ON cloud_sync_changes(tenant_id, workspace_id, table_name, server_seq);

CREATE TABLE cloud_sync_conflicts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  table_name text NOT NULL CHECK (table_name ~ '^[a-z][a-z0-9_]*$'),
  row_id uuid NOT NULL,
  record jsonb NOT NULL CHECK (jsonb_typeof(record) = 'object'),
  bytes integer NOT NULL CHECK (bytes >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id, workspace_id) REFERENCES workspaces(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX cloud_sync_conflicts_scope_id ON cloud_sync_conflicts(tenant_id, workspace_id, id);

CREATE TABLE cloud_sync_idempotency (
  tenant_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  idempotency_key text NOT NULL CHECK (length(idempotency_key) BETWEEN 1 AND 512),
  payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
  response jsonb NOT NULL CHECK (jsonb_typeof(response) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, workspace_id, idempotency_key),
  FOREIGN KEY (tenant_id, workspace_id) REFERENCES workspaces(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX cloud_sync_idempotency_expiry ON cloud_sync_idempotency(created_at);

CREATE TABLE cloud_sync_refs (
  tenant_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  child_table text NOT NULL,
  child_row uuid NOT NULL,
  parent_table text NOT NULL,
  parent_row uuid NOT NULL,
  PRIMARY KEY (tenant_id, workspace_id, child_table, child_row, parent_table, parent_row),
  FOREIGN KEY (tenant_id, workspace_id) REFERENCES workspaces(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX cloud_sync_refs_parent ON cloud_sync_refs(tenant_id, workspace_id, parent_table, parent_row);

-- One durable cache invalidation per accepted server sequence. A missing DO
-- acknowledgement leaves the record retryable; the DO applies max(seq), so
-- delivery is idempotent and never makes the cache regress.
CREATE TABLE cloud_sync_outbox (
  tenant_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  server_seq bigint NOT NULL CHECK (server_seq > 0),
  delivered_at timestamptz,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  PRIMARY KEY (tenant_id, workspace_id, server_seq),
  FOREIGN KEY (tenant_id, workspace_id) REFERENCES workspaces(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX cloud_sync_outbox_pending ON cloud_sync_outbox(tenant_id, workspace_id, server_seq) WHERE delivered_at IS NULL;
CREATE INDEX cloud_sync_outbox_delivered ON cloud_sync_outbox(delivered_at) WHERE delivered_at IS NOT NULL;

-- `xyra_app_login` from core/0001 is the shared least-privilege privilege bundle.
-- The Worker URL connects as the separately provisioned `xyra_cloud_runtime_app` login.
-- Local migration chains may not have that credential provisioned, so create only a
-- NOLOGIN placeholder when absent. Never create/promote a login or set a password here.
DO $$
DECLARE
  runtime_oid oid;
  bundle_oid oid;
  owned_count integer;
  membership_count integer;
BEGIN
  SELECT oid INTO bundle_oid FROM pg_roles WHERE rolname='xyra_app_login';
  IF bundle_oid IS NULL THEN
    RAISE EXCEPTION 'xyra_app_login bundle is missing';
  END IF;
  IF EXISTS (
    SELECT 1 FROM pg_roles WHERE oid=bundle_oid
      AND (rolsuper OR rolcreatedb OR rolcreaterole OR rolbypassrls)
  ) THEN
    RAISE EXCEPTION 'xyra_app_login has unsafe role attributes';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='xyra_cloud_runtime_app') THEN
    CREATE ROLE xyra_cloud_runtime_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
  SELECT oid INTO runtime_oid FROM pg_roles WHERE rolname='xyra_cloud_runtime_app';
  IF EXISTS (
    SELECT 1 FROM pg_roles WHERE oid=runtime_oid
      AND (rolsuper OR rolcreatedb OR rolcreaterole OR rolbypassrls)
  ) THEN
    RAISE EXCEPTION 'xyra_cloud_runtime_app has unsafe role attributes';
  END IF;

  SELECT count(*) INTO owned_count FROM (
    SELECT oid FROM pg_class WHERE relowner=runtime_oid
    UNION ALL SELECT oid FROM pg_proc WHERE proowner=runtime_oid
    UNION ALL SELECT oid FROM pg_namespace WHERE nspowner=runtime_oid
    UNION ALL SELECT oid FROM pg_type WHERE typowner=runtime_oid
  ) owned;
  IF owned_count <> 0 THEN
    RAISE EXCEPTION 'xyra_cloud_runtime_app must not own database objects';
  END IF;

  SELECT count(*) INTO owned_count FROM (
    SELECT oid FROM pg_class WHERE relowner=bundle_oid
    UNION ALL SELECT oid FROM pg_proc WHERE proowner=bundle_oid
    UNION ALL SELECT oid FROM pg_namespace WHERE nspowner=bundle_oid
    UNION ALL SELECT oid FROM pg_type WHERE typowner=bundle_oid
  ) owned;
  IF owned_count <> 0 THEN
    RAISE EXCEPTION 'xyra_app_login must not own database objects';
  END IF;

  -- A runtime login may have no memberships yet, or exactly the reviewed bundle
  -- membership from a prior controlled setup. Reject all other inherited roles.
  SELECT count(*) INTO membership_count FROM pg_auth_members WHERE member=runtime_oid;
  IF membership_count > 1 OR EXISTS (
    SELECT 1 FROM pg_auth_members
     WHERE member=runtime_oid AND roleid<>bundle_oid
  ) THEN
    RAISE EXCEPTION 'xyra_cloud_runtime_app has unexpected role memberships';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_auth_members WHERE member=bundle_oid) THEN
    RAISE EXCEPTION 'xyra_app_login has unexpected role memberships';
  END IF;
END $$;
ALTER ROLE xyra_app_login NOLOGIN;
GRANT xyra_app_login TO xyra_cloud_runtime_app WITH INHERIT TRUE, SET FALSE, ADMIN FALSE;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'cloud_sync_sequences','cloud_sync_rows','cloud_sync_field_seq','cloud_sync_changes',
    'cloud_sync_conflicts','cloud_sync_idempotency','cloud_sync_refs','cloud_sync_outbox'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

CREATE POLICY cloud_sync_sequences_scope ON cloud_sync_sequences USING
  (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true))
  WITH CHECK (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true));
CREATE POLICY cloud_sync_rows_scope ON cloud_sync_rows USING
  (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true))
  WITH CHECK (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true));
CREATE POLICY cloud_sync_field_seq_scope ON cloud_sync_field_seq USING
  (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true))
  WITH CHECK (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true));
CREATE POLICY cloud_sync_changes_scope ON cloud_sync_changes USING
  (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true))
  WITH CHECK (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true));
CREATE POLICY cloud_sync_conflicts_scope ON cloud_sync_conflicts USING
  (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true))
  WITH CHECK (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true));
CREATE POLICY cloud_sync_idempotency_scope ON cloud_sync_idempotency USING
  (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true))
  WITH CHECK (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true));
CREATE POLICY cloud_sync_refs_scope ON cloud_sync_refs USING
  (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true))
  WITH CHECK (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true));
CREATE POLICY cloud_sync_outbox_scope ON cloud_sync_outbox USING
  (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true))
  WITH CHECK (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true));
-- The Worker may enumerate minimal pending invalidation metadata cross-tenant for Cron recovery.
-- Writes still use the tenant/workspace policy above and therefore need an explicit scope.
CREATE POLICY cloud_sync_outbox_dispatch_read ON cloud_sync_outbox FOR SELECT TO xyra_app_login USING (true);
CREATE POLICY cloud_sync_outbox_cleanup ON cloud_sync_outbox FOR DELETE TO xyra_app_login USING
  (tenant_id::text=current_setting('app.tenant_id',true) AND workspace_id::text=current_setting('app.workspace_id',true)
   AND delivered_at < now() - interval '30 days');

-- Core 0001 policies name its privilege-bundle role in current_user checks. The Worker connects
-- as xyra_cloud_runtime_app, so grant only these specific role-scoped operations there as well.
CREATE POLICY cloud_dpop_replays_expired_cleanup_runtime ON cloud_dpop_replays
  FOR DELETE TO xyra_cloud_runtime_app USING (expires_at < now());
CREATE POLICY cloud_webhook_receipts_runtime ON cloud_webhook_receipts
  FOR ALL TO xyra_cloud_runtime_app
  USING (current_user='xyra_cloud_runtime_app') WITH CHECK (current_user='xyra_cloud_runtime_app');
CREATE POLICY cloud_cron_runs_runtime ON cloud_cron_runs
  FOR ALL TO xyra_cloud_runtime_app
  USING (current_user='xyra_cloud_runtime_app') WITH CHECK (current_user='xyra_cloud_runtime_app');

GRANT SELECT, INSERT ON cloud_sync_sequences TO xyra_app_login;
GRANT UPDATE (last_seq) ON cloud_sync_sequences TO xyra_app_login;
GRANT SELECT, INSERT ON cloud_sync_rows TO xyra_app_login;
GRANT UPDATE (fields,deleted_hlc,updated_at) ON cloud_sync_rows TO xyra_app_login;
GRANT SELECT, INSERT, DELETE ON cloud_sync_field_seq TO xyra_app_login;
GRANT UPDATE (server_seq) ON cloud_sync_field_seq TO xyra_app_login;
GRANT SELECT, INSERT, DELETE ON cloud_sync_changes TO xyra_app_login;
GRANT UPDATE (change,bytes) ON cloud_sync_changes TO xyra_app_login;
GRANT SELECT, INSERT ON cloud_sync_conflicts TO xyra_app_login;
GRANT SELECT, INSERT, DELETE ON cloud_sync_idempotency TO xyra_app_login;
GRANT SELECT, INSERT, DELETE ON cloud_sync_refs TO xyra_app_login;
GRANT SELECT, INSERT, DELETE ON cloud_sync_outbox TO xyra_app_login;
GRANT UPDATE (delivered_at,attempts) ON cloud_sync_outbox TO xyra_app_login;
GRANT USAGE, SELECT ON SEQUENCE cloud_sync_conflicts_id_seq TO xyra_app_login;
