import { defineCapability } from '@xyra/contracts';
import { z } from 'zod';

export const MemoryType = z.enum(['preference', 'fact', 'project_state', 'decision', 'procedure', 'tool_knowledge', 'historical_outcome']);
export type MemoryType = z.infer<typeof MemoryType>;
export const TrustLevel = z.enum(['untrusted', 'user', 'reviewed', 'authoritative']);
export const SourceDraft = z.strictObject({ sourceType: z.string().min(1).max(80), title: z.string().min(1).max(500), uri: z.string().max(2_000).nullable().optional(), externalBlobRefs: z.array(z.uuid()).max(50).default([]), trustLevel: TrustLevel.default('untrusted'), retention: z.string().min(1).max(100).default('workspace') });
export const IngestDraft = z.strictObject({ source: SourceDraft, content: z.string().min(1).max(2_000_000), contentType: z.string().min(1).max(200), capturedAt: z.iso.datetime({ offset: true }).optional(), chunkSize: z.number().int().min(128).max(20_000).default(1_200), overlap: z.number().int().min(0).max(2_000).default(100), embeddings: z.array(z.array(z.number().finite()).min(1)).optional(), embeddingModel: z.string().min(1).optional(), embeddingVersion: z.string().min(1).optional() }).superRefine((d, ctx) => {
  if (d.embeddings && (!d.embeddingModel || !d.embeddingVersion)) ctx.addIssue({ code: 'custom', path: ['embeddingModel'], message: 'Embedding model and version are required when embeddings are supplied' });
});
export const ClaimDraft = z.strictObject({ signalId: z.uuid(), subject: z.string().min(1).max(1_000), predicate: z.string().min(1).max(500), object: z.string().min(1).max(4_000), confidence: z.number().min(0).max(1), effectiveFrom: z.iso.datetime({ offset: true }), effectiveTo: z.iso.datetime({ offset: true }).nullable().optional() });
export const SignalInput = z.strictObject({ sourceId: z.uuid(), sourceVersionId: z.uuid(), chunkId: z.uuid().nullable().optional(), signalType: z.string().min(1).max(100), payload: z.record(z.string(), z.unknown()).default({}) });
export const PromotionInput = z.strictObject({ claimId: z.uuid(), authorityType: z.enum(['reviewer', 'policy']), authorityReference: z.string().min(1).max(500), reason: z.string().min(1).max(2_000), supersedesId: z.uuid().optional() });
export const ProcedureInput = z.strictObject({ title: z.string().min(1).max(300), type: z.enum(['skill', 'sop', 'xyra_pattern']), body: z.string().min(1).max(50_000), successfulRunId: z.uuid().optional() });
export const ProcedureReviewInput = z.strictObject({ procedureId: z.uuid(), decision: z.enum(['approved', 'rejected']) });
export const ProcedureListInput = z.strictObject({ limit: z.number().int().min(1).max(100).default(50), status: z.enum(['candidate', 'approved', 'rejected']).optional() });
export const ErasureRequestInput = z.strictObject({ sourceId: z.uuid() });
export const ErasureRetryInput = z.strictObject({ erasureId: z.uuid(), approvalRequestId: z.uuid() });
export const ErasureStatusInput = z.strictObject({ erasureId: z.uuid(), limit: z.number().int().min(1).max(100).default(25), cursor: z.strictObject({ occurredAt: z.iso.datetime({ offset: true }), id: z.uuid() }).optional() });
export const ErasureStatusOutput = z.object({ id: z.uuid(), sourceId: z.uuid(), status: z.literal('waiting_cloud'), attempts: z.number().int(), retentionPolicy: z.string(), externalBlobRefs: z.array(z.uuid()), lastErrorCode: z.string().nullable(), completionReceipt: z.null() });
export const ErasureAuditOutput = z.object({ items: z.array(z.object({ id: z.uuid(), outcome: z.string(), checked_blob_refs: z.array(z.uuid()), deleted_blob_refs: z.array(z.uuid()), retention_policy: z.string(), audit_reference: z.string().nullable(), error_code: z.string().nullable(), occurred_at: z.iso.datetime({ offset: true }) }).passthrough()), nextCursor: z.strictObject({ occurredAt: z.iso.datetime({ offset: true }), id: z.uuid() }).nullable() });
export const ErasureStatusResult = z.object({ id: z.uuid(), sourceId: z.uuid(), status: z.enum(['waiting_cloud', 'retryable_failure', 'local_purge_pending', 'complete']), attempts: z.number().int(), retentionPolicy: z.string(), externalBlobRefs: z.array(z.uuid()), lastErrorCode: z.string().nullable(), completionReceipt: z.string().nullable(), audit: ErasureAuditOutput });
export const MemoryDraft = z.strictObject({ memoryType: MemoryType, title: z.string().min(1).max(300), content: z.string().min(1).max(20_000), sourceId: z.uuid().nullable().optional(), sourceVersionId: z.uuid().nullable().optional(), confidence: z.number().min(0).max(1).nullable().optional(), importance: z.number().min(0).max(1).nullable().optional(), effectiveFrom: z.iso.datetime({ offset: true }).nullable().optional(), effectiveTo: z.iso.datetime({ offset: true }).nullable().optional(), supersedesId: z.uuid().nullable().optional() });
export const MemoryListInput = z.strictObject({ limit: z.number().int().min(1).max(100).default(25), memoryType: MemoryType.optional(), cursor: z.strictObject({ updatedAt: z.iso.datetime({ offset: true }), id: z.uuid() }).optional() });
export const MemoryListOutput = z.object({ items: z.array(z.object({ id: z.uuid(), memory_type: MemoryType, title: z.string(), content: z.string(), updated_at: z.iso.datetime({ offset: true }) }).passthrough()), nextCursor: z.strictObject({ updatedAt: z.iso.datetime({ offset: true }), id: z.uuid() }).nullable() });
export const SearchInput = z.strictObject({ query: z.string().min(1).max(2_000), limit: z.number().int().min(1).max(50).default(10), vector: z.array(z.number().finite()).optional(), embeddingModel: z.string().optional(), embeddingVersion: z.string().optional() });
export const brainCapabilities = {
  ingest: defineCapability({ id: 'brain.sources.ingest', title: 'Ingest source', description: 'Store a provenance-bearing source version and chunks', kind: 'write', permission: 'brain:source:write', input: IngestDraft, output: z.object({ sourceId: z.uuid(), versionId: z.uuid(), chunkIds: z.array(z.uuid()) }), emits: ['brain.source.ingested'] }),
  search: defineCapability({ id: 'brain.knowledge.search', title: 'Search knowledge', description: 'Search authorized workspace knowledge and return cited untrusted excerpts', kind: 'read', permission: 'brain:source:read', input: SearchInput, output: z.array(z.object({ sourceId: z.uuid(), sourceVersionId: z.uuid(), chunkId: z.uuid(), citation: z.string(), content: z.string(), score: z.number(), untrusted: z.literal(true) })) }),
  memories: defineCapability({ id: 'brain.memories.list', title: 'List memory', description: 'Page through memory scoped to the current workspace', kind: 'read', permission: 'brain:memory:read', input: MemoryListInput, output: MemoryListOutput }),
  createClaim: defineCapability({ id: 'brain.claims.create', title: 'Record claim', description: 'Record an evidence-linked claim for review; this does not promote a Fact', kind: 'write', permission: 'brain:source:write', input: ClaimDraft, output: z.object({ id: z.uuid(), contradictions: z.array(z.uuid()) }), agentCallable: true }),
  createSignal: defineCapability({ id: 'brain.signals.create', title: 'Record evidence signal', description: 'Attach an extraction or review signal to a scoped source version and optional chunk', kind: 'write', permission: 'brain:source:write', input: SignalInput, output: z.object({ signalId: z.uuid() }), agentCallable: true }),
  promoteClaim: defineCapability({ id: 'brain.facts.promote', title: 'Promote claim to Fact', description: 'Promote a claim with reviewer or authorized policy provenance', kind: 'write', permission: 'brain:truth:review', input: PromotionInput, output: z.object({ factId: z.uuid(), promotionId: z.uuid(), supersedesId: z.uuid().nullable() }), agentCallable: false, emits: ['brain.truth.promoted'] }),
  proposeProcedure: defineCapability({ id: 'brain.procedures.propose', title: 'Propose procedure', description: 'Create a versioned pending procedure candidate', kind: 'write', permission: 'brain:source:write', input: ProcedureInput, output: z.object({ procedureId: z.uuid() }), agentCallable: true }),
  reviewProcedure: defineCapability({ id: 'brain.procedures.review', title: 'Review procedure', description: 'Append a reviewer decision as a new procedure version', kind: 'write', permission: 'brain:truth:review', input: ProcedureReviewInput, output: z.object({ procedureId: z.uuid() }), agentCallable: false, emits: ['brain.procedure.reviewed'] }),
  procedures: defineCapability({ id: 'brain.procedures.list', title: 'List procedures', description: 'List scoped procedure candidates and reviewed versions', kind: 'read', permission: 'brain:source:read', input: ProcedureListInput, output: z.array(z.object({ id: z.uuid(), title: z.string(), procedure_type: z.string(), status: z.string(), version: z.number().int(), procedure_id: z.uuid() }).passthrough()) }),
  requestErasure: defineCapability({ id: 'brain.sources.erase', title: 'Request source erasure', description: 'Persist approved erasure intent; actual purge waits for privileged local and CLOUD reference-check/audit workflows', kind: 'consequential', permission: 'brain:source:erase', approvalPolicy: 'brain.sources.erase', input: ErasureRequestInput, output: ErasureStatusOutput, agentCallable: false, emits: ['brain.source.erasure.pending'] }),
  retryErasure: defineCapability({ id: 'brain.sources.erase.retry', title: 'Retry source erasure', description: 'Record a bounded retry for an approved waiting erasure intent', kind: 'consequential', permission: 'brain:source:erase', approvalPolicy: 'brain.sources.erase.retry', input: ErasureRetryInput, output: ErasureStatusOutput, agentCallable: false }),
  erasureStatus: defineCapability({ id: 'brain.sources.erase.status', title: 'Read source erasure status and paged retention evidence', description: 'Read scoped erasure state and bounded retry audit history', kind: 'read', permission: 'brain:source:read', input: ErasureStatusInput, output: ErasureStatusResult }),
};
