import { defineModule } from '@xyra/contracts';

export default defineModule({
  id: 'brain',
  version: '1.0.0',
  pillar: 'BRAIN',
  title: 'Knowledge & Memory',
  description: 'Source grounded knowledge, governed truth and scoped memory',
  icon: 'brain',
  order: 20,
  requirements: [
    'XIO-REQ-BRN-001', 'XIO-REQ-BRN-002', 'XIO-REQ-BRN-003', 'XIO-REQ-BRN-004', 'XIO-REQ-BRN-005',
    'REQ-DATA-001', 'REQ-DATA-002', 'REQ-DATA-005', 'REQ-003', 'REQ-008',
  ],
  permissions: ['brain:source:read', 'brain:source:write', 'brain:source:erase', 'brain:memory:read', 'brain:memory:write', 'brain:truth:review'],
  roleGrants: {
    owner: ['brain:source:read', 'brain:source:write', 'brain:source:erase', 'brain:memory:read', 'brain:memory:write', 'brain:truth:review'],
    admin: ['brain:source:read', 'brain:source:write', 'brain:source:erase', 'brain:memory:read', 'brain:memory:write', 'brain:truth:review'],
    manager: ['brain:source:read', 'brain:source:write', 'brain:memory:read', 'brain:memory:write', 'brain:truth:review'],
    member: ['brain:source:read', 'brain:source:write', 'brain:memory:read', 'brain:memory:write'],
    viewer: ['brain:source:read', 'brain:memory:read'],
    auditor: ['brain:source:read', 'brain:memory:read'],
  },
  nav: [
    { path: '', title: 'Knowledge', keywords: ['sources', 'search', 'library'] },
    { path: 'truth', title: 'Truth engine', keywords: ['claims', 'facts', 'contradictions'] },
    { path: 'procedures', title: 'Procedures', keywords: ['skills', 'sops', 'workflows'] },
  ],
  events: { emits: ['brain.source.ingested', 'brain.truth.promoted', 'brain.procedure.reviewed'], consumes: ['workflow.pattern.succeeded'] },
  tables: [
    { name: 'brain_sources', class: 'lww', authority: 'synced', actorField: 'created_by', receivedAtField: 'created_at', writePermission: 'brain:source:write', readPermission: 'brain:source:read', allowedFields: ['source_type', 'title', 'uri', 'trust_level', 'retention'], columns: { source_type: { type: 'text', requiredOnInsert: true, minLength: 1 }, title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 500 }, uri: { type: 'text', nullable: true }, trust_level: { type: 'text', requiredOnInsert: true }, retention: { type: 'text' }, created_by: { type: 'uuid', requiredOnInsert: true }, created_at: { type: 'timestamptz' } } },
    { name: 'brain_source_versions', class: 'append', authority: 'append', actorField: 'created_by', receivedAtField: 'created_at', writePermission: 'brain:source:write', readPermission: 'brain:source:read', allowedFields: ['source_id', 'version', 'content_hash', 'content_type', 'content_text', 'captured_at'], columns: { source_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_sources' } }, version: { type: 'integer', requiredOnInsert: true, min: '1' }, content_hash: { type: 'text', requiredOnInsert: true }, content_type: { type: 'text', requiredOnInsert: true }, content_text: { type: 'text', nullable: true }, captured_at: { type: 'timestamptz', requiredOnInsert: true }, created_by: { type: 'uuid', requiredOnInsert: true }, created_at: { type: 'timestamptz' } } },
    // Vector fields are derived by the trusted local service and deliberately excluded from synced writes.
    { name: 'brain_chunks', class: 'append', authority: 'append', actorField: 'created_by', receivedAtField: 'created_at', writePermission: 'brain:source:write', readPermission: 'brain:source:read', allowedFields: ['source_id', 'source_version_id', 'ordinal', 'content_hash', 'content_text'], columns: { source_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_sources' } }, source_version_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_source_versions' } }, ordinal: { type: 'integer', requiredOnInsert: true, min: '0' }, content_hash: { type: 'text', requiredOnInsert: true }, content_text: { type: 'text', requiredOnInsert: true }, created_by: { type: 'uuid', requiredOnInsert: true }, created_at: { type: 'timestamptz' } } },
    { name: 'brain_signals', class: 'append', authority: 'append', actorField: 'created_by', receivedAtField: 'created_at', writePermission: 'brain:source:write', readPermission: 'brain:source:read', allowedFields: ['source_id', 'source_version_id', 'chunk_id', 'signal_type', 'payload'], columns: { source_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_sources' } }, source_version_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_source_versions' } }, chunk_id: { type: 'uuid', nullable: true, references: { table: 'brain_chunks' } }, signal_type: { type: 'text', requiredOnInsert: true }, payload: { type: 'jsonb' }, created_by: { type: 'uuid', requiredOnInsert: true }, created_at: { type: 'timestamptz' } } },
    { name: 'brain_claims', class: 'append', authority: 'append', actorField: 'created_by', receivedAtField: 'created_at', writePermission: 'brain:source:write', readPermission: 'brain:source:read', allowedFields: ['signal_id', 'subject', 'predicate', 'object', 'confidence', 'effective_from', 'effective_to'], columns: { signal_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_signals' } }, subject: { type: 'text', requiredOnInsert: true }, predicate: { type: 'text', requiredOnInsert: true }, object: { type: 'text', requiredOnInsert: true }, confidence: { type: 'numeric', requiredOnInsert: true, min: '0', max: '1', scale: 6 }, effective_from: { type: 'timestamptz', requiredOnInsert: true }, effective_to: { type: 'timestamptz', nullable: true }, created_by: { type: 'uuid', requiredOnInsert: true }, created_at: { type: 'timestamptz' } } },
    { name: 'brain_facts', class: 'append', authority: 'append', actorField: 'created_by', receivedAtField: 'created_at', writePermission: 'brain:truth:review', readPermission: 'brain:source:read', allowedFields: ['claim_id', 'subject', 'predicate', 'object', 'confidence', 'effective_from', 'effective_to', 'supersedes_id', 'promotion_id'], columns: { claim_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_claims' } }, subject: { type: 'text', requiredOnInsert: true }, predicate: { type: 'text', requiredOnInsert: true }, object: { type: 'text', requiredOnInsert: true }, confidence: { type: 'numeric', requiredOnInsert: true, min: '0', max: '1', scale: 6 }, effective_from: { type: 'timestamptz', requiredOnInsert: true }, effective_to: { type: 'timestamptz', nullable: true }, supersedes_id: { type: 'uuid', nullable: true, references: { table: 'brain_facts' } }, promotion_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_promotions' } }, created_by: { type: 'uuid', requiredOnInsert: true }, created_at: { type: 'timestamptz' } } },
    { name: 'brain_memories', class: 'lww', authority: 'synced', actorField: 'created_by', receivedAtField: 'created_at', writePermission: 'brain:memory:write', readPermission: 'brain:memory:read', allowedFields: ['memory_type', 'title', 'content', 'source_id', 'source_version_id', 'confidence', 'importance', 'effective_from', 'effective_to', 'supersedes_id'], columns: { memory_type: { type: 'text', requiredOnInsert: true }, title: { type: 'text', requiredOnInsert: true }, content: { type: 'text', requiredOnInsert: true }, source_id: { type: 'uuid', nullable: true, references: { table: 'brain_sources' } }, source_version_id: { type: 'uuid', nullable: true, references: { table: 'brain_source_versions' } }, confidence: { type: 'numeric', nullable: true, min: '0', max: '1', scale: 6 }, importance: { type: 'numeric', nullable: true, min: '0', max: '1', scale: 6 }, effective_from: { type: 'timestamptz', nullable: true }, effective_to: { type: 'timestamptz', nullable: true }, supersedes_id: { type: 'uuid', nullable: true, references: { table: 'brain_memories' } }, created_by: { type: 'uuid', requiredOnInsert: true }, created_at: { type: 'timestamptz' } } },
    { name: 'brain_contradictions', class: 'append', authority: 'append', actorField: 'created_by', receivedAtField: 'created_at', writePermission: 'brain:truth:review', readPermission: 'brain:source:read', allowedFields: ['claim_id', 'fact_id', 'status', 'resolution'], columns: { claim_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_claims' } }, fact_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_facts' } }, status: { type: 'text', requiredOnInsert: true }, resolution: { type: 'text', nullable: true }, created_by: { type: 'uuid', requiredOnInsert: true }, created_at: { type: 'timestamptz' } } },
    { name: 'brain_promotions', class: 'append', authority: 'append', actorField: 'created_by', receivedAtField: 'created_at', writePermission: 'brain:truth:review', readPermission: 'brain:source:read', allowedFields: ['claim_id', 'reviewer_id', 'authority_type', 'authority_ref', 'reason'], columns: { claim_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_claims' } }, reviewer_id: { type: 'uuid', requiredOnInsert: true }, authority_type: { type: 'text', requiredOnInsert: true }, authority_ref: { type: 'text', requiredOnInsert: true }, reason: { type: 'text', requiredOnInsert: true }, created_by: { type: 'uuid', requiredOnInsert: true }, created_at: { type: 'timestamptz' } } },
    { name: 'brain_procedures', class: 'append', authority: 'append', actorField: 'created_by', receivedAtField: 'created_at', writePermission: 'brain:truth:review', readPermission: 'brain:source:read', allowedFields: ['procedure_id', 'version', 'title', 'procedure_type', 'body', 'status', 'source_run_id', 'reviewed_by'], columns: { procedure_id: { type: 'uuid', requiredOnInsert: true }, version: { type: 'integer', requiredOnInsert: true, min: '1' }, title: { type: 'text', requiredOnInsert: true }, procedure_type: { type: 'text', requiredOnInsert: true }, body: { type: 'text', requiredOnInsert: true }, status: { type: 'text', requiredOnInsert: true }, source_run_id: { type: 'uuid', nullable: true }, reviewed_by: { type: 'uuid', nullable: true }, created_by: { type: 'uuid', requiredOnInsert: true }, created_at: { type: 'timestamptz' } } },
    { name: 'brain_source_erasures', class: 'local', authority: 'local' },
    { name: 'brain_source_erasure_attempts', class: 'append', authority: 'append', actorField: 'actor_id', receivedAtField: 'occurred_at', writePermission: 'brain:source:erase', readPermission: 'brain:source:read', allowedFields: ['erasure_id', 'outcome', 'checked_blob_refs', 'deleted_blob_refs', 'retention_policy', 'audit_reference', 'error_code'], columns: { erasure_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'brain_source_erasures' } }, outcome: { type: 'text', requiredOnInsert: true }, checked_blob_refs: { type: 'jsonb' }, deleted_blob_refs: { type: 'jsonb' }, retention_policy: { type: 'text', requiredOnInsert: true }, audit_reference: { type: 'text', nullable: true }, error_code: { type: 'text', nullable: true }, actor_id: { type: 'uuid', requiredOnInsert: true }, occurred_at: { type: 'timestamptz' } } },
  ],
  dataClassification: 'confidential',
});
