import { defineModule } from '@xyra/contracts';

export default defineModule({
  id: 'invest',
  version: '1.0.0',
  pillar: 'INTEL',
  title: 'Invest',
  description: 'Portfolio and investment operations on the shared ledger',
  icon: 'chart-no-axes-combined',
  requirements: ['REQ-INV-001'],
  permissions: [
    'invest:portfolio:read',
    'invest:portfolio:write',
    'invest:portfolio:fund',
    'invest:mandate:read',
    'invest:mandate:manage',
    'invest:mandate:vote',
    'invest:mandate:approve',
    'invest:market:read',
    'invest:market:ingest',
    'invest:order:read',
    'invest:order:propose',
    'invest:order:approve',
    'invest:order:execute',
    'invest:order:cancel',
    'invest:order:kill_switch',
    'invest:breach:manage',
    'invest:backtest:run',
    'invest:performance:report',
    'invest:signal:consume',
  ],
  roleGrants: {
    owner: [
      'invest:portfolio:read', 'invest:portfolio:write', 'invest:portfolio:fund', 'invest:mandate:read', 'invest:mandate:manage', 'invest:mandate:vote', 'invest:mandate:approve',
      'invest:market:read', 'invest:market:ingest', 'invest:order:read', 'invest:order:propose',
      'invest:order:approve', 'invest:order:execute', 'invest:order:cancel', 'invest:order:kill_switch', 'invest:breach:manage', 'invest:backtest:run', 'invest:performance:report', 'invest:signal:consume',
    ],
    admin: [
      'invest:portfolio:read', 'invest:portfolio:write', 'invest:portfolio:fund', 'invest:mandate:read', 'invest:mandate:manage', 'invest:mandate:vote', 'invest:mandate:approve',
      'invest:market:read', 'invest:market:ingest', 'invest:order:read', 'invest:order:propose',
      'invest:order:approve', 'invest:order:execute', 'invest:order:cancel', 'invest:order:kill_switch', 'invest:breach:manage', 'invest:backtest:run', 'invest:performance:report', 'invest:signal:consume',
    ],
    manager: [
      'invest:portfolio:read', 'invest:portfolio:write', 'invest:portfolio:fund', 'invest:mandate:read', 'invest:market:read',
      'invest:market:ingest', 'invest:backtest:run',
      'invest:order:read', 'invest:order:propose', 'invest:order:cancel',
    ],
    member: ['invest:portfolio:read', 'invest:mandate:read', 'invest:market:read', 'invest:order:read'],
    viewer: ['invest:portfolio:read', 'invest:mandate:read', 'invest:market:read', 'invest:order:read'],
    auditor: ['invest:portfolio:read', 'invest:mandate:read', 'invest:market:read', 'invest:order:read'],
  },
  nav: [
    { path: '', title: 'Portfolio', keywords: ['positions', 'NAV', 'assets'] },
    { path: 'orders', title: 'Paper orders', keywords: ['trade', 'paper', 'fills'] },
    { path: 'risk', title: 'Risk and mandates', keywords: ['guardrails', 'limits', 'policy'] },
    { path: 'backtests', title: 'PAPER backtests', keywords: ['simulation', 'OHLC', 'research'] },
    { path: 'performance', title: 'PAPER performance', keywords: ['TWR', 'benchmark', 'statements'] },
  ],
  dependsOn: ['money', 'swarm', 'flow'],
  tables: [
    { name: 'invest_instruments', class: 'local', authority: 'server', readPermission: 'invest:market:read', serverReadCapabilities: ['invest_paper_execution'], serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_portfolios', class: 'local', authority: 'server', readPermission: 'invest:portfolio:read', serverReadCapabilities: ['invest_paper_execution'], serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_mandates', class: 'append', authority: 'server', readPermission: 'invest:mandate:read', serverReadCapabilities: ['invest_paper_execution'], serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_market_prices', class: 'append', authority: 'server', readPermission: 'invest:market:read', serverReadCapabilities: ['invest_paper_execution'], serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_restricted_rules', class: 'append', authority: 'server', readPermission: 'invest:mandate:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_risk_decisions', class: 'append', authority: 'server', readPermission: 'invest:order:read', serverWriteCapabilities: ['invest_paper', 'invest_paper_execution'] },
    { name: 'invest_orders', class: 'local', authority: 'server', readPermission: 'invest:order:read', serverWriteCapabilities: ['invest_paper', 'invest_paper_execution'] },
    { name: 'invest_order_events', class: 'append', authority: 'server', readPermission: 'invest:order:read', serverWriteCapabilities: ['invest_paper', 'invest_paper_execution'] },
    { name: 'invest_fills', class: 'append', authority: 'server', readPermission: 'invest:order:read', serverWriteCapabilities: ['invest_paper', 'invest_paper_execution'] },
    { name: 'invest_breaches', class: 'local', authority: 'server', readPermission: 'invest:breach:manage', serverWriteCapabilities: ['invest_paper', 'invest_paper_execution'] },
    { name: 'invest_market_sessions', class: 'append', authority: 'server', readPermission: 'invest:market:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_tax_lots', class: 'local', authority: 'server', readPermission: 'invest:order:read', serverWriteCapabilities: ['invest_paper_execution'] },
    { name: 'invest_tax_lot_events', class: 'append', authority: 'server', readPermission: 'invest:order:read', serverWriteCapabilities: ['invest_paper_execution'] },
    { name: 'invest_breach_events', class: 'append', authority: 'server', readPermission: 'invest:breach:manage', serverWriteCapabilities: ['invest_paper', 'invest_paper_execution'] },
    { name: 'invest_reconciliation_runs', class: 'append', authority: 'server', readPermission: 'invest:breach:manage', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_reconciliation_discrepancies', class: 'append', authority: 'server', readPermission: 'invest:breach:manage', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_reconciliation_events', class: 'append', authority: 'server', readPermission: 'invest:breach:manage', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_custody_dispatches', class: 'local', authority: 'server', readPermission: 'invest:breach:manage', serverReadCapabilities: ['invest_paper'], serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_signal_decisions', class: 'append', authority: 'server', readPermission: 'invest:order:read', serverReadCapabilities: ['invest_paper'], serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_portfolio_risk_state', class: 'local', authority: 'server', readPermission: 'invest:breach:manage', serverWriteCapabilities: ['invest_paper', 'invest_paper_execution'] },
    { name: 'invest_limit_changes', class: 'append', authority: 'server', readPermission: 'invest:mandate:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_ic_memos', class: 'local', authority: 'server', readPermission: 'invest:mandate:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_ic_votes', class: 'append', authority: 'server', readPermission: 'invest:mandate:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_ic_memo_events', class: 'append', authority: 'server', readPermission: 'invest:mandate:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_backtest_datasets', class: 'append', authority: 'server', readPermission: 'invest:market:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_backtest_strategies', class: 'append', authority: 'server', readPermission: 'invest:market:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_backtest_runs', class: 'append', authority: 'server', readPermission: 'invest:market:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_performance_marks', class: 'append', authority: 'server', readPermission: 'invest:portfolio:read', serverWriteCapabilities: ['invest_paper', 'invest_paper_execution'] },
    { name: 'invest_performance_reports', class: 'append', authority: 'server', readPermission: 'invest:portfolio:read', serverWriteCapabilities: ['invest_paper'] },
  ],
  portedFrom: ['FounderOS trading guardrails and strategy reference (MIT)'],
});
