import { defineModule } from '@xyra/contracts';

export default defineModule({
  id: 'invest',
  version: '1.0.0',
  pillar: 'INTEL',
  title: 'Invest',
  description: 'Portfolio and investment operations on the shared ledger',
  icon: 'chart-no-axes-combined',
  requirements: ['REQ-INV-001'],
  permissions: [
    'invest:portfolio:read',
    'invest:portfolio:write',
    'invest:mandate:read',
    'invest:mandate:manage',
    'invest:market:read',
    'invest:market:ingest',
    'invest:order:read',
    'invest:order:propose',
    'invest:order:approve',
    'invest:order:cancel',
    'invest:breach:manage',
  ],
  roleGrants: {
    owner: [
      'invest:portfolio:read', 'invest:portfolio:write', 'invest:mandate:read', 'invest:mandate:manage',
      'invest:market:read', 'invest:market:ingest', 'invest:order:read', 'invest:order:propose',
      'invest:order:approve', 'invest:order:cancel', 'invest:breach:manage',
    ],
    admin: [
      'invest:portfolio:read', 'invest:portfolio:write', 'invest:mandate:read', 'invest:mandate:manage',
      'invest:market:read', 'invest:market:ingest', 'invest:order:read', 'invest:order:propose',
      'invest:order:approve', 'invest:order:cancel', 'invest:breach:manage',
    ],
    manager: [
      'invest:portfolio:read', 'invest:portfolio:write', 'invest:mandate:read', 'invest:market:read',
      'invest:order:read', 'invest:order:propose', 'invest:order:cancel',
    ],
    member: ['invest:portfolio:read', 'invest:mandate:read', 'invest:market:read', 'invest:order:read'],
    viewer: ['invest:portfolio:read', 'invest:mandate:read', 'invest:market:read', 'invest:order:read'],
    auditor: ['invest:portfolio:read', 'invest:mandate:read', 'invest:market:read', 'invest:order:read'],
  },
  nav: [
    { path: '', title: 'Portfolio', keywords: ['positions', 'NAV', 'assets'] },
    { path: 'orders', title: 'Paper orders', keywords: ['trade', 'paper', 'fills'] },
    { path: 'risk', title: 'Risk and mandates', keywords: ['guardrails', 'limits', 'policy'] },
  ],
  dependsOn: ['money'],
  tables: [
    { name: 'invest_instruments', class: 'local', authority: 'server', readPermission: 'invest:market:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_portfolios', class: 'local', authority: 'server', readPermission: 'invest:portfolio:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_mandates', class: 'append', authority: 'server', readPermission: 'invest:mandate:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_market_prices', class: 'append', authority: 'server', readPermission: 'invest:market:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_restricted_rules', class: 'append', authority: 'server', readPermission: 'invest:mandate:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_risk_decisions', class: 'append', authority: 'server', readPermission: 'invest:order:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_orders', class: 'local', authority: 'server', readPermission: 'invest:order:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_order_events', class: 'append', authority: 'server', readPermission: 'invest:order:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_fills', class: 'append', authority: 'server', readPermission: 'invest:order:read', serverWriteCapabilities: ['invest_paper'] },
    { name: 'invest_breaches', class: 'local', authority: 'server', readPermission: 'invest:breach:manage', serverWriteCapabilities: ['invest_paper'] },
  ],
  portedFrom: ['FounderOS trading guardrails and strategy reference (MIT)'],
});
