import { defineModule } from '@xyra/contracts';

export default defineModule({
  id: 'core',
  version: '1.0.0',
  pillar: 'PLATFORM',
  title: 'Workspace',
  description: 'Identity, approvals, audit and settings',
  icon: 'settings',
  order: 10,
  requirements: ['REQ-CORP-001', 'REQ-SEC-004'],
  permissions: [
    'core:workspace:read',
    'core:workspace:write',
    'core:approval:read',
    'core:approval:decide',
    'core:audit:read',
    'core:audit:append',
    'core:event:append',
    'core:approval:request',
    'core:settings:read',
    'core:settings:write',
  ],
  roleGrants: {
    manager: [
      'core:workspace:read',
      'core:approval:read',
      'core:approval:request',
      'core:audit:append',
      'core:event:append',
      'core:settings:read',
      'core:settings:write',
    ],
    member: [
      'core:workspace:read',
      'core:approval:request',
      'core:audit:append',
      'core:event:append',
      'core:settings:read',
    ],
    viewer: ['core:workspace:read', 'core:settings:read'],
    auditor: ['core:workspace:read', 'core:audit:read', 'core:settings:read'],
  },
  nav: [
    { path: '', title: 'Workspace', keywords: ['organization', 'members'] },
    {
      path: 'approvals',
      title: 'Approvals',
      keywords: ['decisions', 'requests'],
      permission: 'core:approval:read',
    },
    { path: 'audit', title: 'Audit', keywords: ['activity', 'history'], permission: 'core:audit:read' },
    { path: 'settings', title: 'Settings', keywords: ['preferences'], permission: 'core:settings:read' },
  ],
  tables: [
    { name: 'tenants', class: 'lww', authority: 'server' },
    { name: 'workspaces', class: 'lww', authority: 'server' },
    { name: 'users', class: 'lww', authority: 'server' },
    { name: 'memberships', class: 'lww', authority: 'server' },
    {
      name: 'approval_requests',
      class: 'append',
      authority: 'append',
      actorField: 'requested_by',
      receivedAtField: 'created_at',
      writePermission: 'core:approval:request',
      readPermission: 'core:approval:read',
      allowedFields: ['capability_id', 'input_hash', 'reason', 'expires_at'],
      columns: {
        capability_id: { type: 'text', requiredOnInsert: true },
        input_hash: { type: 'text', requiredOnInsert: true },
        reason: { type: 'text', requiredOnInsert: true },
        expires_at: { type: 'timestamptz', requiredOnInsert: true },
        requested_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    { name: 'approval_decisions', class: 'append', authority: 'server' },
    {
      name: 'audit_events',
      class: 'append',
      authority: 'append',
      actorField: 'actor_id',
      receivedAtField: 'received_at',
      writePermission: 'core:audit:append',
      readPermission: 'core:audit:read',
      allowedFields: ['action', 'target_type', 'target_id', 'detail', 'occurred_at'],
      columns: {
        action: { type: 'text', requiredOnInsert: true },
        target_type: { type: 'text', requiredOnInsert: true },
        target_id: { type: 'text', nullable: true },
        detail: { type: 'jsonb', maxBytes: 65_536 },
        occurred_at: { type: 'timestamptz' },
        actor_id: { type: 'uuid', requiredOnInsert: true },
        received_at: { type: 'timestamptz' },
      },
    },
    {
      name: 'domain_events',
      class: 'append',
      authority: 'append',
      actorField: 'actor_id',
      receivedAtField: 'received_at',
      writePermission: 'core:event:append',
      readPermission: 'core:workspace:read',
      allowedFields: ['event_type', 'aggregate_id', 'payload', 'occurred_at'],
      columns: {
        event_type: { type: 'text', requiredOnInsert: true },
        aggregate_id: { type: 'text', requiredOnInsert: true },
        payload: { type: 'jsonb', requiredOnInsert: true, maxBytes: 262_144 },
        occurred_at: { type: 'timestamptz' },
        actor_id: { type: 'uuid', requiredOnInsert: true },
        received_at: { type: 'timestamptz' },
      },
    },
    { name: 'workspace_settings', class: 'lww', authority: 'server' },
    // Cloud auth/security state is Worker-owned and never accepted from device sync.
    { name: 'cloud_passkeys', class: 'lww', authority: 'server' },
    { name: 'cloud_auth_transactions', class: 'lww', authority: 'server' },
    { name: 'cloud_auth_codes', class: 'lww', authority: 'server' },
    { name: 'cloud_refresh_families', class: 'lww', authority: 'server' },
    { name: 'cloud_refresh_tokens', class: 'lww', authority: 'server' },
    { name: 'cloud_dpop_replays', class: 'lww', authority: 'server' },
    { name: 'cloud_webhook_receipts', class: 'lww', authority: 'server' },
    { name: 'cloud_queue_jobs', class: 'lww', authority: 'server' },
    { name: 'cloud_cron_runs', class: 'lww', authority: 'server' },
    { name: 'cloud_purge_markers', class: 'lww', authority: 'server' },
  ],
});
