import { defineModule } from '@xyra/contracts';

export default defineModule({
  id: 'ops',
  version: '1.0.0',
  pillar: 'COMMAND',
  title: 'Operations',
  description: 'Projects and tasks in one operating view',
  icon: 'list-checks',
  order: 10,
  requirements: ['REQ-004', 'XIO-REQ-CMD-001'],
  permissions: ['ops:project:read', 'ops:project:write', 'ops:task:read', 'ops:task:write'],
  roleGrants: {
    manager: ['ops:project:read', 'ops:project:write', 'ops:task:read', 'ops:task:write'],
    member: ['ops:project:read', 'ops:task:read', 'ops:task:write'],
    viewer: ['ops:project:read', 'ops:task:read'],
    auditor: ['ops:project:read', 'ops:task:read'],
  },
  nav: [
    { path: '', title: 'Projects', keywords: ['work', 'portfolio'] },
    { path: 'tasks', title: 'Tasks', keywords: ['assignments', 'board'] },
  ],
  dependsOn: ['core'],
  tables: [
    {
      name: 'ops_projects',
      class: 'lww',
      authority: 'synced',
      guardedColumns: ['status'],
      actorField: 'created_by',
      writePermission: 'ops:project:write',
      readPermission: 'ops:project:read',
      receivedAtField: 'created_at',
      allowedFields: ['name', 'description'],
      columns: {
        name: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 200 },
        description: { type: 'text' },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    {
      name: 'ops_tasks',
      class: 'lww',
      authority: 'synced',
      guardedColumns: ['status'],
      actorField: 'created_by',
      writePermission: 'ops:task:write',
      readPermission: 'ops:task:read',
      receivedAtField: 'created_at',
      allowedFields: ['project_id', 'title', 'description', 'assignee_id', 'due_at'],
      columns: {
        project_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'ops_projects' } },
        title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 300 },
        description: { type: 'text' },
        assignee_id: { type: 'uuid', nullable: true },
        due_at: { type: 'timestamptz', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
  ],
});
