import { defineModule } from '@xyra/contracts';

export default defineModule({
  id: 'command',
  version: '1.0.0',
  pillar: 'COMMAND',
  title: 'Command',
  description: 'Executive console: dashboard, chat, approvals, alerts, blueprint, doctor and personas',
  icon: 'layout-dashboard',
  order: 5,
  requirements: [
    'XIO-REQ-OPS-001',
    'REQ-PAR-001',
    'REQ-003',
    'REQ-008',
    'REQ-012',
    'PAR-XIO-004',
    'PAR-XIO-070',
    'PAR-XIO-071',
    'PAR-XIO-072',
    'PAR-XIO-073',
  ],
  permissions: [
    'command:dashboard:read',
    'command:chat:read',
    'command:chat:write',
    'command:alert:read',
    'command:alert:write',
    'command:action:read',
    'command:action:write',
    'command:blueprint:read',
    'command:doctor:read',
    'command:persona:read',
  ],
  roleGrants: {
    manager: [
      'command:dashboard:read',
      'command:chat:read',
      'command:chat:write',
      'command:alert:read',
      'command:alert:write',
      'command:action:read',
      'command:action:write',
      'command:blueprint:read',
      'command:doctor:read',
      'command:persona:read',
    ],
    member: [
      'command:dashboard:read',
      'command:chat:read',
      'command:chat:write',
      'command:alert:read',
      'command:action:read',
      'command:blueprint:read',
      'command:doctor:read',
      'command:persona:read',
    ],
    viewer: [
      'command:dashboard:read',
      'command:chat:read',
      'command:alert:read',
      'command:action:read',
      'command:blueprint:read',
      'command:doctor:read',
      'command:persona:read',
    ],
    auditor: [
      'command:dashboard:read',
      'command:alert:read',
      'command:action:read',
      'command:doctor:read',
    ],
  },
  nav: [
    { path: '', title: 'Home', keywords: ['dashboard', 'command center'] },
    { path: 'chats', title: 'Chats', keywords: ['chat', 'conductor', 'messages'] },
    { path: 'approvals', title: 'Approvals', keywords: ['inbox', 'decisions'] },
    { path: 'alerts', title: 'Alerts', keywords: ['notifications', 'warnings'] },
    { path: 'blueprint', title: 'Blueprint', keywords: ['system map', 'canvas'] },
    { path: 'doctor', title: 'Doctor', keywords: ['health', 'diagnostics'] },
    { path: 'personas', title: 'Personas', keywords: ['templates', 'business types'] },
  ],
  dependsOn: ['core'],
  tables: [
    {
      name: 'command_dashboard_layouts',
      class: 'lww',
      authority: 'synced',
      actorField: 'updated_by',
      writePermission: 'command:dashboard:read',
      readPermission: 'command:dashboard:read',
      allowedFields: ['widgets'],
      columns: {
        widgets: { type: 'jsonb' },
        updated_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'command_alerts',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'command:alert:write',
      readPermission: 'command:alert:read',
      allowedFields: ['title', 'body', 'severity', 'dismissed_at'],
      columns: {
        title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 200 },
        body: { type: 'text' },
        severity: { type: 'text', enum: ['info', 'warning', 'critical'] },
        dismissed_at: { type: 'timestamptz', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'command_actions',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'command:action:write',
      readPermission: 'command:action:read',
      allowedFields: ['title', 'body', 'priority', 'done_at', 'dismissed_at'],
      columns: {
        title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 200 },
        body: { type: 'text' },
        priority: { type: 'text', enum: ['low', 'normal', 'high'] },
        done_at: { type: 'timestamptz', nullable: true },
        dismissed_at: { type: 'timestamptz', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'command_chats',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'command:chat:write',
      readPermission: 'command:chat:read',
      allowedFields: ['title', 'agent_id', 'status'],
      columns: {
        title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 200 },
        agent_id: { type: 'text', nullable: true },
        status: { type: 'text', enum: ['active', 'archived'] },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'command_chat_messages',
      class: 'append',
      authority: 'append',
      actorField: 'created_by',
      writePermission: 'command:chat:write',
      readPermission: 'command:chat:read',
      receivedAtField: 'created_at',
      allowedFields: ['chat_id', 'role', 'content'],
      columns: {
        chat_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'command_chats' } },
        role: { type: 'text', requiredOnInsert: true, enum: ['user', 'agent', 'system'] },
        content: { type: 'text', requiredOnInsert: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    {
      name: 'command_blueprint_nodes',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'command:blueprint:read',
      readPermission: 'command:blueprint:read',
      allowedFields: ['label', 'kind', 'x', 'y', 'meta'],
      columns: {
        label: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 200 },
        kind: {
          type: 'text',
          requiredOnInsert: true,
          enum: ['operator', 'agent', 'department', 'connector', 'store', 'page', 'daemon', 'model', 'skill'],
        },
        x: { type: 'integer' },
        y: { type: 'integer' },
        meta: { type: 'jsonb' },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'command_blueprint_edges',
      class: 'append',
      authority: 'append',
      actorField: 'created_by',
      writePermission: 'command:blueprint:read',
      readPermission: 'command:blueprint:read',
      receivedAtField: 'created_at',
      allowedFields: ['source_id', 'target_id', 'label'],
      columns: {
        source_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'command_blueprint_nodes' } },
        target_id: { type: 'uuid', requiredOnInsert: true, references: { table: 'command_blueprint_nodes' } },
        label: { type: 'text', nullable: true },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
    {
      name: 'command_personas',
      class: 'lww',
      authority: 'synced',
      actorField: 'created_by',
      writePermission: 'command:persona:read',
      readPermission: 'command:persona:read',
      allowedFields: ['title', 'summary', 'pillars', 'north_star_metric'],
      columns: {
        title: { type: 'text', requiredOnInsert: true, minLength: 1, maxLength: 200 },
        summary: { type: 'text' },
        north_star_metric: { type: 'text', nullable: true },
        pillars: { type: 'jsonb' },
        created_by: { type: 'uuid', requiredOnInsert: true },
      },
    },
    {
      name: 'command_doctor_checks',
      class: 'append',
      authority: 'append',
      actorField: 'created_by',
      writePermission: 'command:doctor:read',
      readPermission: 'command:doctor:read',
      receivedAtField: 'created_at',
      allowedFields: ['check_id', 'status', 'detail'],
      columns: {
        check_id: { type: 'text', requiredOnInsert: true },
        status: { type: 'text', requiredOnInsert: true, enum: ['healthy', 'degraded', 'unhealthy'] },
        detail: { type: 'text' },
        created_by: { type: 'uuid', requiredOnInsert: true },
        created_at: { type: 'timestamptz' },
      },
    },
  ],
  portedFrom: ['FounderOS (MIT) @ ad46d77'],
});
